### ISSUE TITLE
Computed properties should return null value by default

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-behavior#89]
addon/mixins/component.js

**Comment by juwara0** [comment]
@notmessenger: I am working this

**Comment by juwara0** [comment]
This can be closed because the only computed property in this mixin is showContent() which should not return a null by default but rather a Boolean and by default it already defaults to a return of false: https://github.com/softlayer/sl-ember-behavior/blob/396017f1f1eb73338eca7500e45d16310fbe3fdb/addon/mixins/component.js#L65

**Comment by juwara0** [comment]
@notmessenger: this issue can be closed
